apiVersion: v1
kind: Service
metadata:
  name: veille-service
spec:
  selector:
    app: veille
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer


  